### ISSUE TITLE
Problem accessing mage through default loadbalancer ip address/port on AKS

### ISSUE THREAD

**Issue by lambertsbennett** [mage-ai/helm-charts#34]
I tried deploying mage on AKS and followed the guide. Everything starts up happily and looking at the logs everything seems fine. However, when I try to access the external IP address I get a connection timeout. I'm guessing something is going on with the service definition, but I tried to alter it in various ways and I haven't been able to solve the problem. 

I'm wondering if this is an isolated problem or if there is something wrong with the chart?

**Comment by sriniarul** [comment]
could you please post here the guide link you followed to deploy the mage on AWS EKS. 

Meanwhile, you can try these troubleshooting steps.
 1. Make sure the ip/port you are trying to access is resolving using ping and telnet cmd
 2. If u have access to kubectl cli you can proxy the mage server locally to check cluster level issue.
 3. Check the AWS load balancer server health and check with the DNS name:port of the load balancer
 
 I can able to help you when you provide more information.

**Comment by lambertsbennett** [comment]
@sriniarul I followed the guide here: https://docs.mage.ai/production/deploying-to-cloud/using-helm. 
and set up my storage following the example https://github.com/mage-ai/helm-charts/blob/master/examples/aks/azure-files-pvc.yaml.

Importantly this is on Azure AKS and not AWS EKS. I will try out the other things that you mentioned and report back.

**Comment by sriniarul** [comment]
ohh! i see. Anyway try to proxy the service to localhost and let me know whether it works or not.
https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

**Comment by lambertsbennett** [comment]
Ok so:
- When I ping the IP address and port the request times out.
- When I port forward and then try to ssh to the machine I see that it sees an incoming request and tries to handle it.

**Comment by sriniarul** [comment]
> Ok so:
> 
> * When I ping the IP address and port the request times out.
> * When I port forward and then try to ssh to the machine I see that it sees an incoming request and tries to handle it.

via port forward can u able to access mage

**Comment by sriniarul** [comment]
@lambertsbennett let me know in any way I can help you.

**Comment by sriniarul** [comment]
@lambertsbennett let me know in any way I can help you.
